# Azure DevOps AI Agent Pipeline
# Triggered by incoming webhook from service hook when work item is updated
#
# This is the STANDALONE version - use directly for GitHub template users.
# For org-specific customization (webhook name, docker image), see examples/azure-pipelines.yml
#
# Required pipeline variables (set in Azure DevOps):
#   OPENCODE_AUTH_JSON - OpenCode authentication JSON
#
# Optional variables:
#   DOCKER_IMAGE - Override default OpenCode docker image
#   TEAMS_WEBHOOK_URL - Teams webhook for notifications

resources:
  webhooks:
    - webhook: WorkItemEvent
      connection: ai-agent-trigger

trigger: none

variables:
  # Default docker image - override in pipeline variables for org-specific image
  dockerImage: ${{ coalesce(variables['DOCKER_IMAGE'], 'ghcr.io/opencode-ai/opencode:latest') }}

stages:
  # Stage 1: Process webhook and determine action
  - template: stages/process.yml
    parameters:
      webhookPayload: ${{ parameters.WorkItemEvent }}

  # Stage 2: Analyze work item (when ai-ready tag is added)
  - template: stages/analyze.yml
    parameters:
      dockerImage: $(dockerImage)

  # Stage 3: Implement solution (when ai-approved tag is added)
  - template: stages/implement.yml
    parameters:
      dockerImage: $(dockerImage)

  # Stage 4: Execute AI command (when @ai mention in comment)
  - template: stages/command.yml
    parameters:
      dockerImage: $(dockerImage)

  # Stage 5: Skip (no actionable tags)
  - template: stages/skip.yml
